### ISSUE TITLE
Image's platform does not match for Raspberry Pi 4

### ISSUE THREAD

**Issue by nigiriemoji** [Charles94jp/NameSilo-DDNS#10]
Greetings, I am trying to use DDNS in a docker container for namesilo using the docker run command provided in the github. My issue is that it seems like arm64/v8 isn't supported and there are only amd64 builds available. I am running a Raspberry Pi 4 via dietpi/raspbian. Any chance to add additional support for this?

`root@DietPi:~/docker# docker run -d --name ddns -v /docker/namesilo/:/home/NameSilo-DDNS:rw charles94jp/ddns
# --restart=always

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
e815e9a71dfd8c7cc7ed752086f299e90a854c726b9321e2a1938061e4a60c5d`

Thank you

**Comment by Charles94jp** [comment]
I rebuilt the image and pushed it to docker hub. 
> https://hub.docker.com/r/charles94jp/ddns/tags

Please try again. Delete the old image first and then pull the new one.
If it still doesn't work, you can clone the repository and build the docker image manually

**Comment by nigiriemoji** [comment]
Thank you, I was able to get my docker run command to load. But I am unable to find any configuration or any other files in my /docker/namesilo/ folder. Could you please tell me how to generate this in a container? My command that I ran is same as above but I will paste below

`docker run -d --name ddns -v /docker/namesilo/:/home/NameSilo-DDNS:rw charles94jp/ddns`

nvm i got found it.

**Comment by nigiriemoji** [comment]
How do I know if the updates have successfully been pushed to Namesilo? I don't see any logs in Portainer's view of DDNS' logs

I have 2 DNS records created in namesilo already. 

- Hostname blank, Type A, IP is my home IP (already entered before doing this app)
- Hostname jellyfin, Type A, IP is my home IP (already entered before doing this app)

My conf.json looks like this:
```
{
    "domains": [
        "jellyfin.mydomain.com", "mydomain.com"
    ],
    "key": "my api key",
    "frequency": 600,
    "mail_host": "",
    "mail_port": "",
    "mail_user": "",
    "mail_pass": "",
    "receivers": [""],
    "email_after_reboot": false,
    "auto_restart": true,
    "email_every_update": false


```

**Comment by Charles94jp** [comment]
Updates can be viewed through the log.
In the case of docker, because `-v /docker/namesilo/:/home/NameSilo-DDNS:rw` was used during `docker run`
You can run `/docker/namesilo/ddns-docker` to view the logs, or just view the file `/docker/namesilo/log/DDNS.log`
