### ISSUE TITLE
help：how to fix "list_dns_api "error？

### ISSUE THREAD

**Issue by myworksfun** [Charles94jp/NameSilo-DDNS#12]
![Snipaste_2022-09-03_15-32-55](https://user-images.githubusercontent.com/45185967/188260896-80b62858-43e2-4cb4-9988-f8775b1110b5.png)
docker环境，ddns镜像latest，namesilo的有3个域名，conf.json中的domain和key配置正确，且key为可读写。
重启ddns后出现上述错误，请问可能的原因是什么？

**Comment by Charles94jp** [comment]
麻烦提供一下配置文件，key请脱敏。
提供一下 log/DDNS.log 最后十几行，有堆栈信息的话都列出来

**Comment by myworksfun** [comment]
> 
**conf.json配置文件内容如下：**
{
    "domains": [
        "docker.*****.top"
    ],
    "domains_ipv6": [
        "ipv6.namesilo.com"
    ],
    "key": "c88**********29f7",
    "frequency": 600,
    "mail_host": "smtp.qq.com",
    "mail_port": "465",
    "mail_user": "",
    "mail_pass": "password or key",
    "receivers": [""],
    "mail_lang": "zh-cn",
    "auto_restart": false,
    "email_every_update": false
}
**DDNS.log文件日志很少，见下截图：**
![log2](https://user-images.githubusercontent.com/45185967/188264086-0c9cc9dd-d6e1-403a-98f7-a6f9003979a5.png)

**Comment by Charles94jp** [comment]
把`domains_ipv6`里的内容删掉🤣这个是示例，你没有这个域名
或许我模板里不应该放内容在里面

**Comment by myworksfun** [comment]
> 把`domains_ipv6`里的内容删掉🤣这个是示例，你没有这个域名 或许我模板里不应该放内容在里面

哈哈哈，果然凑效，多谢大佬指点😄
