### ISSUE TITLE
Does not support domain with both A and AAAA records

### ISSUE THREAD

**Issue by calvinchai** [Charles94jp/NameSilo-DDNS#13]
When I have 
` "domains": [
        "hpe.example.com"
    ],
    "domains_ipv6": [
        "hpe.example.com"
    ],`
Every time fetching the current record, only A record will be returned, which then caused the program to update the A record with an ipv6 address and yields 
```2022-09-28 09:10:39,199 - namesilo_client.py[line:174] - ERROR: update_dns_api: ip type and domain type do not match
<?xml version="1.0"?>
<namesilo><request><operation>dnsUpdateRecord</operation><ip>73.4.114.xxx</ip></request><reply><code>280</code><detail>2601:180:8300:1df6:b12d:3410:b7c5:xxxx must be a valid ipv4</detail></reply></namesilo>```

**Comment by Charles94jp** [comment]
The domain name in domains and the domain name in domains_ipv6 cannot be filled with the same domain name. You should create a subdomain of type A on namesilo and put it in domains, and then create a subdomain of type AAAA and put it in domains_ipv6.

**Comment by calvinchai** [comment]
Oh okay. I was wondering if the program can check the existing record and update it based on the type, but it seems namesilo doesn't allow updating the record for specific type.

**Comment by calvinchai** [comment]
Actually, you can get the specific id and update the record with the id. Would you consider add this feature so the domain could be resolved for both ipv4 and ipv6?

**Comment by Charles94jp** [comment]
The program can update both ipv4 and ipv6 addresses at the same time as long as the domain and domains_ipv6 are filled in correctly. If the program checks that the record types do not match, it will stop running after logging.
 Refer to line 170 of [lib/namesilo_client.py](https://github.com/Charles94jp/NameSilo-DDNS/blob/python/lib/namesilo_client.py#L170).

**Comment by calvinchai** [comment]
I mean one domain with both ipv4 and ipv6 address, I changed the code a little bit and I think it works now. I created a pull request.
