### ISSUE TITLE
请求的 ip 链接的会挂掉

### ISSUE THREAD

**Issue by ArmsZhou** [Charles94jp/NameSilo-DDNS#17]
███╗   ██╗  █████╗  ███╗   ███╗ ███████╗ ███████╗ ██╗ ██╗       ██████╗      ██████╗  ██████╗  ███╗   ██╗ ███████╗
 ████╗  ██║ ██╔══██╗ ████╗ ████║ ██╔════╝ ██╔════╝ ██║ ██║      ██╔═══██╗     ██╔══██╗ ██╔══██╗ ████╗  ██║ ██╔════╝
 ██╔██╗ ██║ ███████║ ██╔████╔██║ █████╗   ███████╗ ██║ ██║      ██║   ██║     ██║  ██║ ██║  ██║ ██╔██╗ ██║ ███████╗
 ██║╚██╗██║ ██╔══██║ ██║╚██╔╝██║ ██╔══╝   ╚════██║ ██║ ██║      ██║   ██║     ██║  ██║ ██║  ██║ ██║╚██╗██║ ╚════██║
 ██║ ╚████║ ██║  ██║ ██║ ╚═╝ ██║ ███████╗ ███████║ ██║ ███████╗ ╚██████╔╝     ██████╔╝ ██████╔╝ ██║ ╚████║ ███████║
 ╚═╝  ╚═══╝ ╚═╝  ╚═╝ ╚═╝     ╚═╝ ╚══════╝ ╚══════╝ ╚═╝ ╚══════╝  ╚═════╝      ╚═════╝  ╚═════╝  ╚═╝  ╚═══╝ ╚══════╝
 
Traceback (most recent call last):
  File "/home/NameSilo-DDNS/ddns.py", line 226, in <module>
    main()
  File "/home/NameSilo-DDNS/ddns.py", line 222, in main
    ddns.start()
  File "/home/NameSilo-DDNS/ddns.py", line 151, in start
    self._namesilo_client.fetch_domains_info()
  File "/home/NameSilo-DDNS/lib/namesilo_client.py", line 80, in fetch_domains_info
    self._list_dns_api(domain)
  File "/home/NameSilo-DDNS/lib/namesilo_client.py", line 108, in _list_dns_api
    r = r.split('</record_id>')
AttributeError: 'list' object has no attribute 'split'

**Comment by Charles94jp** [comment]
这边没法复现，可能是网络原因，可以试试重启。

**Comment by huangzhuxing** [comment]
[https://github.com/Charles94jp/NameSilo-DDNS/pull/24](https://github.com/Charles94jp/NameSilo-DDNS/pull/24) 参考此处修复
