### ISSUE TITLE
考虑出一个dockerfile么

### ISSUE THREAD

**Issue by ddv12138** [Charles94jp/NameSilo-DDNS#2]
docker会方便很多，开机启动也不用systemctrl那一套了，部署在家里服务器上，服务器来电自启，开机自动连接

**Comment by Charles94jp** [comment]
好的，尽快安排

**Comment by Charles94jp** [comment]
好了，构建一下试试，应该可以了
> https://github.com/Charles94jp/NameSilo-DDNS/blob/python/readme.zh-CN.md#Docker
> > https://github.com/Charles94jp/NameSilo-DDNS/commit/f6b78b9ee326beed717411677d8762308dd61691
