### ISSUE TITLE
能否每次检测到iP变更，就发送一个提醒邮件

### ISSUE THREAD

**Issue by ddv12138** [Charles94jp/NameSilo-DDNS#3]
提个建议，因为ddns改namesilo托管的域名的dns，在国内生效时间较长，而动态ip实际变动频率不高，能否增加一个功能，每次检测到ip变更就在修改dns纪录的同时，发送邮件提醒，邮件内可附上最新iP，来让我知道最近访问的时候有域名的解析记录不是最新的风险

**Comment by Charles94jp** [comment]
可以考虑，之前觉得这样会有点吵，访问服务器频率不高的话，几乎感受不到dns切换的那十几二十分钟。目前只在向namesilo推送新ip时，如果失败，才会发邮件告知新IP。这样程序显得静默一点

**Comment by yzxcxya** [comment]
太强了大佬 @Charles94jp

**Comment by aalennku** [comment]
serverchan server酱 推送信息到微信岂不是更优雅？

**Comment by ddv12138** [comment]
可能我是个例，如果使用namesilo托管，那么每次生效需要十几分钟到几小时不等，所以提了这个issue，后来我实在忍受不了，切换到国内的dnspod了

**Comment by Shunamxiao** [comment]
> 可以考虑，之前觉得这样会有点吵，访问服务器频率不高的话，几乎感受不到dns切换的那十几二十分钟。目前只在向namesilo推送新IP时，如果失败，才会发邮件告知新IP。这样程序显得静默一点

我也觉得只要ip变了就提醒多爽
