### ISSUE TITLE
能不能把这个TTL改成3600

### ISSUE THREAD

**Issue by Shunamxiao** [Charles94jp/NameSilo-DDNS#30]
![image](https://github.com/Charles94jp/NameSilo-DDNS/assets/92215296/e9951352-1ff1-45ea-965d-9d9b8972f8e3)
能不能把这个改成3600，这样推送新ip后这个更新速度会快一点吧，大佬

**Comment by Charles94jp** [comment]
可以，这两天安排一下
（￣︶￣）↗

**Comment by Shunamxiao** [comment]
> 可以，这两天安排一下 （￣︶￣）↗

大佬不搞个群交流吗，这么早起来搬砖了

**Comment by Shunamxiao** [comment]
> 可以，这两天安排一下 （ ̄） ̄） ↗

我怎么更新最新的功能

**Comment by Charles94jp** [comment]
docker hub上更新了最新的镜像

**Comment by Shunamxiao** [comment]
> docker hub上更新了最新的镜像
pull下来就行对吧，感谢大佬
