### ISSUE TITLE
更新完子域名,怎么更新一级域名

### ISSUE THREAD

**Issue by efarv** [Charles94jp/NameSilo-DDNS#7]
如果域名是a.com,子域名b.a.com,更新完了b.a.com的地址,那怎么更新a.com的地址,用chame指向子域名报错,求解?

**Comment by Charles94jp** [comment]
目前只支持更新`a.b.c`格式的子域名，诸如`s.a.b.c`、`b.c`格式的都不支持

**Comment by efarv** [comment]
so,有什么办法解决吗,还是说ddns都是这个样子,不限厂商

**Comment by Charles94jp** [comment]
只是我的脚本不支持🤣 有空我可以弄一下

**Comment by efarv** [comment]
namesilo解析应该怎么配置,@.a.com   这个应该怎么写,这应该是namesilo配置的问题

**Comment by Charles94jp** [comment]
脚本的话直接配置`@.a.com`，它会拿这个去向namesilo提交，如果解析不了，就是namesilo不支持吧

**Comment by efarv** [comment]
我用的不是你的脚本,所以我只是请教一下这方面的问题.
后面的人如果也遇到类似这样的问题的话,
rrhost参数去掉,rrid对用根域名的record_id
(毕竟解决了问题,所以还是有必要把答案说出来)
