### ISSUE TITLE
Feature Request: Update multiple sub-domains

### ISSUE THREAD

**Issue by kongjun18** [Charles94jp/NameSilo-DDNS#8]
可以把 domain 字段设置为子域名数组吗？一次将多个域名 IP 地址更新为本机地址。

**Google Translate**: Can the domain field be set to an array of subdomains? Update multiple domain IP addresses to local addresses at once.

**Comment by Charles94jp** [comment]
可以实现

**Comment by VIVIDryan** [comment]
也就是说现在如果更新多个子域名的话docker需要开多个实例是吗 @Charles94jp

**Comment by kongjun18** [comment]
> 也就是说现在如果更新多个子域名的话docker需要开多个实例是吗 @Charles94jp

如果你现在需要更新多个子域名的话，可以试试我写的 [namesilo-ddns](https://github.com/kongjun18/namesilo-ddns)。

**Comment by Charles94jp** [comment]
是的 @VIVIDryan 
@kongjun18  666
卷起来了是吧，有空我改改代码吧 😶‍🌫️
