### ISSUE TITLE
能支持ipv6么

### ISSUE THREAD

**Issue by ENCHIGO** [Charles94jp/NameSilo-DDNS#9]

**Comment by Charles94jp** [comment]
目前不支持。需要三个地方都支持才行：
1. 查询本机公网IP的api ：https://2022.ip138.com/
2. 脚本的处理逻辑
3. NameSilo的api

目前脚本逻辑是只用于处理IPv4的，所以不支持。我也没公网IPv6的机器 QAQ
你可去了解一下其余两个是否支持

**Comment by ENCHIGO** [comment]
namesilo api目前是支持的 
我看下能不能完善一下脚本逻辑吧
